In [2]:
import pandas as pd
import numpy as np

w1_x1 = np.array([0.42, -0.2, 1.3, 0.39, -1.6, -0.029, -0.23, 0.27, -1.9, 0.87])
w1_x2 = np.array([-0.087, -3.3, -0.32, 0.71, -5.3, 0.89, 1.9, -0.3, 0.76, -1.0])
w1_x3 = np.array([0.58, -3.4, 1.7, 0.23, -0.15, -4.7, 2.2, -0.87, -2.1, -2.6])

w2_x1 = np.array([-0.4, -0.31, 0.38, -0.15, -0.35, 0.17, -0.011, -0.27, -0.065, -0.12])
w2_x2 = np.array([0.58, 0.27, 0.055, 0.53, 0.47, 0.69, 0.55, 0.61, 0.49, 0.054])
w2_x3 = np.array([0.089, -0.04, -0.0035, 0.011, 0.034, 0.1, -0.18, 0.12, 0.0012, -0.063])

w3_x1 = np.array([0.83, 1.1, -0.44, 0.047, 0.28, -0.39, 0.34, -0.3, 1.1, 0.18])
w3_x2 = np.array([1.6, 1.6, -0.41, -0.45, 0.35, -0.48, -0.079, -0.22, 1.2, -0.11])
w3_x3 = np.array([-0.0014, 0.48, 0.32, 1.4, 3.1, 0.11, 0.14, 2.2, -0.46, -0.49])

data = pd.DataFrame(np.array((w1_x1, w1_x2, w1_x3, w2_x1, w2_x2, w2_x3, w3_x1, w3_x2, w3_x3)).T, columns=('w1_x1', 'w1_x2', 'w1_x3', 'w2_x1', 'w2_x2', 'w2_x3', 'w3_x1', 'w3_x2', 'w3_x3'))

In [3]:
data

w1_x1  w1_x2  w1_x3  w2_x1  w2_x2   w2_x3  w3_x1  w3_x2   w3_x3
0  0.420 -0.087   0.58 -0.400  0.580  0.0890  0.830  1.600 -0.0014
1 -0.200 -3.300  -3.40 -0.310  0.270 -0.0400  1.100  1.600  0.4800
2  1.300 -0.320   1.70  0.380  0.055 -0.0035 -0.440 -0.410  0.3200
3  0.390  0.710   0.23 -0.150  0.530  0.0110  0.047 -0.450  1.4000
4 -1.600 -5.300  -0.15 -0.350  0.470  0.0340  0.280  0.350  3.1000
5 -0.029  0.890  -4.70  0.170  0.690  0.1000 -0.390 -0.480  0.1100
6 -0.230  1.900   2.20 -0.011  0.550 -0.1800  0.340 -0.079  0.1400
7  0.270 -0.300  -0.87 -0.270  0.610  0.1200 -0.300 -0.220  2.2000
8 -1.900  0.760  -2.10 -0.065  0.490  0.0012  1.100  1.200 -0.4600
9  0.870 -1.000  -2.60 -0.120  0.054 -0.0630  0.180 -0.110 -0.4900

In [4]:
data[['w1_x1', 'w1_x2', 'w1_x3']]

w1_x1  w1_x2  w1_x3
0  0.420 -0.087   0.58
1 -0.200 -3.300  -3.40
2  1.300 -0.320   1.70
3  0.390  0.710   0.23
4 -1.600 -5.300  -0.15
5 -0.029  0.890  -4.70
6 -0.230  1.900   2.20
7  0.270 -0.300  -0.87
8 -1.900  0.760  -2.10
9  0.870 -1.000  -2.60

### (a) Write a program to find maximum-likelihood values $\hat{\mu}$ and $\hat{\sigma}$. Apply your program individually to each of the three features $x_i$ of category $\omega_1$ in the table above.

각각의 표본들은 정규분포에서 추출된다고 했을 때 각 표본의 표본분포는

$$ f_{\mu, \sigma^2}(x_i) = \frac{1}{\sigma\sqrt{2\pi}} exp\left(-\frac{(x_i-\mu)^2}{2\sigma^2}\right) $$

이고 $x_1, x_2, \cdots, x_n$ 은 모두 독립적으로 추출했다고 가정하자. 그러면 우도(likelihood)는

$$P(x|\theta) = \prod_{i=1}^{n}f_{\mu, \sigma^2}(x_i) = \prod_{i=1}^{n}\frac{1}{\sigma\sqrt{2\pi}} exp(-\frac{(x_i-\mu)^2}{2\sigma^2})$$

이고, 로그-우도는

$$L(\theta|x) = \sum_{i=1}^{n}log\frac{1}{\sigma\sqrt{2\pi}}exp\left(-\frac{(x_i-\mu)^2}{2\sigma^2}\right)$$

이다. 따라서 $L(\theta|x)$를 $\mu$에 대해 편미분하면,

$$
\frac{\partial L(\theta|x)}{\partial \mu} =-\frac{1}{2\sigma^2}\sum_{i=1}^{n}\frac{\partial}{\partial \mu}\left(x_i^2-2x_i\mu+\mu^2\right)
$$

$$
=-\frac{1}{2\sigma^2}\sum_{i=1}^{n}\left(-2x_i+2\mu\right)
$$

$$
=\frac{1}{\sigma^2}\sum_{i=1}^{n}(x_i-\mu) = \frac{1}{\sigma^2}\left(\sum_{i=1}^{n}x_i-n\mu\right) = 0
$$

따라서 최대우도를 만들어주는 모평균의 추정량은



$$ \hat{\mu} = \frac{1}{n}\sum_{i=1}^{n}x_i $$

이다.

In [18]:
# 최대우도를 만들어주는 모평균의 추정량 (단변량)

def cal_mean(df):
    return df.sum()/len(df)

한편, $L(\theta|x)$를 표준편차 $\sigma$로 편미분하면

$$\frac{\partial L(\theta|x)}{\partial \sigma} = -\frac{n}{\sigma} - \frac{1}{2}\sum_{i=1}^{n}\left(x_i-\mu\right)^2\frac{\partial}{\partial\sigma}\left(\frac{1}{\sigma^2}\right)$$

$$
=-\frac{n}{\sigma}+\frac{1}{\sigma^3}\sum_{i=1}^{n}\left(x_i-\mu\right)^2 = 0
$$

따라서, 최대우도를 만들어주는 모분산의 추정량은

$$\hat{\sigma}^2 = \frac{1}{n}\sum_{i=1}^{n}\left(x_i-\mu\right)^2$$

이라는 것을 알 수 있다.

In [19]:
# 최대우도를 만들어주는 모분산의 추정량 (단변량)

def cal_variance(df):
    return np.sum((df-(df.sum()/len(df)))**2)/len(df)

In [17]:
w1_x1_mean, w1_x2_mean, w1_x3_mean = cal_mean(data[['w1_x1', 'w1_x2', 'w1_x3']])
w1_x1_variance, w1_x2_variance, w1_x3_variance = cal_variance(data[['w1_x1', 'w1_x2', 'w1_x3']])

print("------소숫점 문제로 오차 발생 가능------")
print('Maximum Likelihood mean of estimates w1_x1 : {}'.format(w1_x1_mean))
print('Maximum Likelihood mean of estimates w1_x2 : {}'.format(w1_x2_mean))
print('Maximum Likelihood mean of estimates w1_x3 : {}'.format(w1_x3_mean))
print('----------------------------------------')
print('Maximum Likelihood variance estimates of w1_x1 : {}'.format(w1_x1_variance))
print('Maximum Likelihood variance estimates of w1_x2 : {}'.format(w1_x2_variance))
print('Maximum Likelihood variance estimates of w1_x3 : {}'.format(w1_x3_variance))

------소숫점 문제로 오차 발생 가능------
Maximum Likelihood mean of estimates w1_x1 : -0.07089999999999998
Maximum Likelihood mean of estimates w1_x2 : -0.6047000000000001
Maximum Likelihood mean of estimates w1_x3 : -0.9109999999999999
----------------------------------------
Maximum Likelihood variance estimates of w1_x1 : 0.9061772900000001
Maximum Likelihood variance estimates of w1_x2 : 4.200714809999999
Maximum Likelihood variance estimates of w1_x3 : 4.541949000000001


### (b) Modify your program to apply to two-dimensional Gaussian data $p(\mathbf{x}) \sim N(\boldsymbol{\mu}, \boldsymbol{\sum})$. 

각각의 표본들은 정규분포에서 추출된다고 했을 때 각 표본의 표본분포는

$$\mathbf{x^{(i)}} \sim \mathcal{N}_p(\mu, \Sigma)$$

이고 $\mathbf{x}_1,\mathbf{x}_2, ... ,\mathbf{x}_n$  은 모두 독립적으로 추출했다고 가정하자. 그러면 이고, 로그-우도는(Log-likelihood)는

$$\begin{aligned}
	L(\theta|\mathbf{x}) & = \log \prod_{i=1}^m f_{\mathbf{X^{(i)}}}(\mathbf{x^{(i)} | \mu , \Sigma })
	\\
	& =  \log  \ \prod_{i=1}^m \frac{1}{(2 \pi)^{p/2} |\Sigma|^{1/2}} \exp \left( - \frac{1}{2} \mathbf{(x^{(i)} - \mu)^T \Sigma^{-1} (x^{(i)} - \mu) } \right) 
	\\
	& = \sum_{i=1}^m \left( - \frac{p}{2} \log (2 \pi) - \frac{1}{2} \log |\Sigma|  - \frac{1}{2}   \mathbf{(x^{(i)} - \mu)^T \Sigma^{-1} (x^{(i)} - \mu) }  \right)
\end{aligned}$$

$$
\begin{aligned}
	L(\theta|\mathbf{x}) & = - \frac{mp}{2} \log (2 \pi) - \frac{m}{2} \log |\Sigma|  - \frac{1}{2}  \sum_{i=1}^m  \mathbf{(x^{(i)} - \mu)^T \Sigma^{-1} (x^{(i)} - \mu) }  
\end{aligned}
$$


이다. 따라서 $L(\theta|\mathbf{x})$ 를  $\mu$ 에 대해 편미분하면,

> $\mathbf{ \frac{\partial w^T A w}{\partial w} = 2Aw}$ if $\mathbf{w}$ does not depend on $\mathbf{A}$ and $\mathbf{A}$ is symmetric

$$
\begin{aligned}
	\frac{\partial }{\partial \mu} L(\theta|\mathbf{x}) & = \sum_{i=1}^m  \mathbf{ \Sigma^{-1} ( \mu - x^{(i)} ) }  = 0
	\\ 
	& \text{Since $\Sigma$ is positive definite}
	\\
	0 & = m \mu - \sum_{i=1}^m  \mathbf{  x^{(i)} } 
	\\
	\hat \mu &=  \frac{1}{m} \sum_{i=1}^m \mathbf{  x^{(i)} } = \mathbf{\bar{x}}
\end{aligned}
$$

In [286]:
# 최대우도를 만들어주는 모평균의 추정량 (다변량)

def cal_multivariate_mean(df):
    mat = df.values.tolist()
    means = np.mean(mat, axis=0).tolist()
    return means

한편, $L(\theta|x)$를 $\hat \Sigma$ 로 편미분하면

Deriving the **MLE** for the covariance matrix requires more work and the use of the following linear algebra and calculus properties:

$$
\begin{aligned}
	L(\theta|\mathbf{x})  & = \text{C} - \frac{m}{2} \log |\Sigma|  - \frac{1}{2}  \sum_{i=1}^m  \mathbf{(x^{(i)} - \mu)^T \Sigma^{-1} (x^{(i)} - \mu) }  
	\\
	& = \text{C} + \frac{m}{2} \log |\Sigma^{-1}|  - \frac{1}{2}  \sum_{i=1}^m  tr[ \mathbf{(x^{(i)} - \mu) (x^{(i)} - \mu)^T \Sigma^{-1} }  ]
	\\
	\frac{\partial }{\partial \Sigma^{-1}} L(\theta|\mathbf{x}) & = \frac{m}{2} \Sigma - \frac{1}{2}  \sum_{i=1}^m \mathbf{(x^{(i)} - \mu) (x^{(i)} - \mu)}^T \ \ \text{Since $\Sigma^T = \Sigma$}
\end{aligned}
$$

Equating to zero and solving for $\Sigma$

$$
\begin{aligned}
	0 &= m \Sigma -   \sum_{i=1}^m \mathbf{(x^{(i)} - \mu) (x^{(i)} - \mu)}^T 
	\\
	\hat \Sigma & = \frac{1}{m} \sum_{i=1}^m \mathbf{(x^{(i)} - \hat \mu) (x^{(i)} -\hat  \mu)}^T 
\end{aligned}
$$

In [267]:
# 최대우도를 만들어주는 공분산의 추정량 (다변량)

def cal_multivariate_covariance(df):
    mat = df.values.tolist()
    means = np.mean(mat, axis=0).tolist()
    cov_matrix = []
    for i in range(len(means)):
        covs = []
        for j in range(len(means)):
            sum = 0
            for k in range(sample_n):
                sum += (mat[k][i] - means[i])*(mat[k][j] - means[j])
                result = sum / sample_n
            covs.append(result)
        cov_matrix.append(covs)
    
    return np.reshape(cov_matrix, (len(means), len(means)))

$P(\mathbf{x_1}, \mathbf{x_2}) \sim N(\boldsymbol{\mu}, \boldsymbol{\sum})$

In [287]:
### mean

cal_multivariate_mean(data[['w1_x1', 'w1_x2']])

[-0.07089999999999998, -0.6047000000000001]

In [278]:
# Covariance

cal_multivariate_covariance(data[['w1_x1', 'w1_x2']])

array([[0.90617729, 0.56778177],
       [0.56778177, 4.20071481]])

$P(\mathbf{x_1}, \mathbf{x_3}) \sim N(\boldsymbol{\mu}, \boldsymbol{\sum})$

In [288]:
### mean

cal_multivariate_mean(data[['w1_x1', 'w1_x3']])

[-0.07089999999999998, -0.9109999999999999]

In [289]:
### Covariance

cal_multivariate_covariance(data[['w1_x1', 'w1_x3']])

array([[0.90617729, 0.3940801 ],
       [0.3940801 , 4.541949  ]])

$P(\mathbf{x_2}, \mathbf{x_3}) \sim N(\boldsymbol{\mu}, \boldsymbol{\sum})$

In [290]:
### mean

cal_multivariate_mean(data[['w1_x2', 'w1_x3']])

[-0.6047000000000001, -0.9109999999999999]

In [291]:
### Covariance

cal_multivariate_covariance(data[['w1_x2', 'w1_x3']])

array([[4.20071481, 0.7337023 ],
       [0.7337023 , 4.541949  ]])

###  (c) Modify your program to apply to three-dimensional Gaussian data $p(\mathbf{x}) \sim N(\boldsymbol{\mu}, \boldsymbol{\sum})$. 

In [293]:
### mean

cal_multivariate_mean(data[['w1_x1', 'w1_x2', 'w1_x3']])

[-0.07089999999999998, -0.6047000000000001, -0.9109999999999999]

In [285]:
### Covariance

cal_multivariate_covariance(data[['w1_x1', 'w1_x2','w1_x3']])

array([[0.90617729, 0.56778177, 0.3940801 ],
       [0.56778177, 4.20071481, 0.7337023 ],
       [0.3940801 , 0.7337023 , 4.541949  ]])

### (d) Assume your three-dimensional model is separable, so that 


$$
\sum = diag(\sigma^2_1, \sigma^2_2, \sigma^2_3)
$$ 

 $\quad$Write a program to estimate the mean and the diagonal componentes of $\sum$, Apply your program to the data in $\omega_2$.

In [304]:
### mean

cal_multivariate_mean(data[['w2_x1', 'w2_x2', 'w2_x3']])

[-0.11259999999999999, 0.42989999999999995, 0.006870000000000001]

In [302]:
# 최대우도를 만들어주는 공분산의 추정량 (다변량)

def cal_multivariate_covariance_with_diag(df):
    mat = df.values.tolist()
    means = np.mean(mat, axis=0).tolist()
    cov_matrix = []
    for i in range(len(means)):
        covs = []
        for j in range(len(means)):
            sum = 0
            for k in range(sample_n):
                if i == j:
                    sum += (mat[k][i] - means[i])**2
                    result = sum / sample_n
                else:
                    result = 0 
            covs.append(result)
        cov_matrix.append(covs)
    
    return np.reshape(cov_matrix, (len(means), len(means)))


In [307]:
cal_multivariate_covariance_with_diag(data[['w2_x1', 'w2_x2', 'w2_x3']])

array([[0.05392584, 0.        , 0.        ],
       [0.        , 0.04597009, 0.        ],
       [0.        , 0.        , 0.00711087]])